### PR TITLE
chore: update workflows

### PR DESCRIPTION
**Pull request by distractedm1nd**
Self explanatory. Necessary for #117

### CODE REVIEW

**Comment by MSevey** [comment]
@distractedm1nd currently none of the checks are required for merge. 
Do you want to update that? 
Also is the plan to fix all the red or was this red before?

**Comment by distractedm1nd** [comment]
@MSevey yes, will fix the red and then reopen for review.

I would like the linters and tests to be required for merge - this repo is simple enough that there should never be flakes

**Comment by MSevey** [comment]
> @MSevey yes, will fix the red and then reopen for review.
> 
> I would like the linters and tests to be required for merge - this repo is simple enough that there should never be flakes

Updated

**Review by MSevey — DISMISSED** [review]

**Review by Ferret-san — DISMISSED** [review]
lgtm

**Review by MSevey — APPROVED** [review]

**Review by Ferret-san — APPROVED** [review]
lgtm

**Pull request merged**
