### PR TITLE
ci: general cleanup

### PR DESCRIPTION
**Pull request by ramin**
## Overview

- removes go-input everywhere and relies on go.mod to stay in sync
- updates versions where deprecation is warned (hopefully)
- reconciles the go.mod go version (was mismatched between toolchain and go version during dependabot storm)
- introduces whitespace between workflow job steps for easier reading and aesthetics

### CODE REVIEW

**Review by distractedm1nd — CHANGES_REQUESTED** [review]
No, we can't do this yet - the go mod has to stay at 1.20 for certain integrations

cc @Ferret-san

**Review by MSevey — DISMISSED** [review]
I think @distractedm1nd comment actually justifies this. 
Why would we be advancing the go version in the CI if the go.mod needs to stay. 

All this does is sync the go version being used, and go.mod is the perfect version to go off of. 

👏🏻

**Comment by ramin** [comment]
> No, we can't do this yet - the go mod has to stay at 1.20 for certain integrations
> 
> cc @Ferret-san

left at 1.20

**Review by MSevey — APPROVED** [review]

**Review by distractedm1nd — APPROVED** [review]
Ahh, I thought the api equivalence test would fail considering the go mod there is 1.22. But it passes in this CI

**Pull request merged**
